/*  This file is generated from syscall.def by genisyscall.  */

#ifndef _ISYSCALL_
#define _ISYSCALL_

extern ER i_unl_cpu(void);
extern ER i_loc_cpu(void);
extern ER i_def_svc(FN s_fncd, T_DSVC *pk_dsvc);
extern ER i_ref_sys(T_RSYS *pk_rsys);
extern ER i_ref_cfg(T_RCFG *pk_rcfg);
extern ER i_get_ver(T_VER *pk_ver);
extern ER i_cre_tsk(ID tskid, T_CTSK *pk_ctsk);
extern ER i_del_tsk(ID tskid);
extern ER i_ref_tsk(T_RTSK *pk_rtsk, ID tskid);
extern void i_ext_tsk(void);
extern void i_exd_tsk(void);
extern ER i_sta_tsk(ID tskid, INT stacd);
extern ER i_get_tid(ID *p_tskid);
extern ER i_ter_tsk(ID tskid);
extern ER i_chg_pri(ID tskid, PRI tskpri);
extern ER i_rot_rdq(PRI tskpri);
extern ER i_ena_dsp(void);
extern ER i_dis_dsp(void);
extern ER i_rel_wai(ID tskid);
extern ER i_sus_tsk(ID tskid);
extern ER i_rsm_tsk(ID tskid);
extern ER i_frsm_tsk(ID tskid);
extern ER i_tslp_tsk(TMO tmout);
extern ER i_slp_tsk(void);
extern ER i_wup_tsk(ID tskid);
extern ER i_can_wup(INT *p_wupcnt, ID tskid);
extern ER i_cre_flg(ID flgid, T_CFLG *pk_cflg);
extern ER i_del_flg(ID flgid);
extern ER i_ref_flg(T_RFLG *pk_rflg, ID flgid);
extern ER i_wai_flg(UINT *p_flgptn, ID flgid, UINT waiptn, UINT wfmode);
extern ER i_clr_flg(ID flgid, UINT clrptn);
extern ER i_set_flg(ID flgid, UINT setptn);
extern ER i_cre_sem(ID semid, T_CSEM *pk_csem);
extern ER i_del_sem(ID semid);
extern ER i_ref_sem(T_RSEM *pk_rsem, ID semid);
extern ER i_wai_sem(ID semid);
extern ER i_sig_sem(ID semid);
extern ER i_cre_mbx(ID mbxid, T_CMBX *pk_cmbx);
extern ER i_del_mbx(ID mbxid);
extern ER i_ref_mbx(T_RMBX *pk_rmbx, ID mbxid);
extern ER i_rcv_msg(T_MSG* *ppk_msg, ID mbxid);
extern ER i_snd_msg(ID mbxid, T_MSG *pk_msg);
extern ER i_def_int(UINT dintno, T_DINT *pk_dint);
extern ER i_chg_iXX(UINT iXXXX);
extern ER i_ref_iXX(UINT *p_iXXXX);
extern ER i_ena_int(UINT eintno);
extern ER i_dis_int(UINT eintno);
extern ER i_cre_mpf(ID mpfid, T_CMPF *pk_cmpf);
extern ER i_del_mpf(ID mpfid);
extern ER i_ref_mpf(T_RMPF *pk_rmpf, ID mpfid);
extern ER i_get_blf(VP *p_blf, ID mpfid);
extern ER i_rel_blf(ID mpfid, VP blf);
extern ER i_vget_tim(SYSUTIME *pk_utim);
extern ER i_set_tim(SYSTIME *pk_tim);
extern ER i_get_tim(SYSTIME *pk_tim);
extern ER i_dly_tsk(DLYTIME dlytim);
extern ER i_def_alm(HNO almno, T_DALM *pk_dalm);
extern ER i_def_cyc(HNO cycno, T_DCYC *pk_dcyc);
extern ER i_ref_alm(T_RALM *pk_ralm, HNO almno);
extern ER i_ref_cyc(T_RCYC *pk_rcyc, HNO cycno);
extern ER i_act_cyc(HNO cycno, UINT cycact);
extern ER i_pget_blf(VP *p_blf, ID mpfid);
extern ER i_pget_blk(VP *p_blk, ID mplid, INT blksz);
extern ER i_pol_flg(UINT *p_flgptn, ID flgid, UINT waiptn, UINT wfmode);
extern ER i_preq_sem(ID semid);
extern ER i_prcv_msg(T_MSG* *ppk_msg, ID mbxid);
extern ER i_psnd_mbf(ID mbfid, VP msg, INT msgsz);
extern ER i_prcv_mbf(VP msg, INT *p_msgsz, ID mbfid);
extern ER i_pcal_por(VP msg, INT *p_rmsgsz, ID porid, UINT calptn, INT cmsgsz);
extern ER i_pacp_por(RNO *p_rdvno, VP msg, INT *p_cmsgsz, ID porid, UINT acpptn);
extern ER i_cre_mpl(ID mplid, T_CMPL *pk_cmpl);
extern ER i_del_mpl(ID mplid);
extern ER i_ref_mpl(T_RMPL *pk_rmpl, ID mplid);
extern ER i_get_blk(VP *p_blk, ID mplid, INT blksz);
extern ER i_rel_blk(ID mplid, VP blk);
extern ER i_cre_por(ID porid, T_CPOR *pk_cpor);
extern ER i_del_por(ID porid);
extern ER i_ref_por(T_RPOR *pk_rpor, ID porid);
extern ER i_cal_por(VP msg, INT *p_rmsgsz, ID porid, UINT calptn, INT cmsgsz);
extern ER i_acp_por(RNO *p_rdvno, VP msg, INT *p_cmsgsz, ID porid, UINT acpptn);
extern ER i_rpl_rdv(RNO rdvno, VP msg, INT rmsgsz);
extern ER i_fwd_por(ID porid, UINT calptn, RNO rdvno, VP msg, INT cmsgsz);
extern ER i_cre_mbf(ID mbfid, T_CMBF *pk_cmbf);
extern ER i_del_mbf(ID mbfid);
extern ER i_ref_mbf(T_RMBF *pk_rmbf, ID mbfid);
extern ER i_snd_mbf(ID mbfid, VP msg, INT msgsz);
extern ER i_rcv_mbf(VP msg, INT *p_msgsz, ID mbfid);
extern ER i_tget_blf(VP *p_blf, ID mpfid, TMO tmout);
extern ER i_tget_blk(VP *p_blk, ID mplid, INT blksz, TMO tmout);
extern ER i_twai_flg(UINT *p_flgptn, ID flgid, UINT waiptn, UINT wfmode, TMO tmout);
extern ER i_twai_sem(ID semid, TMO tmout);
extern ER i_trcv_msg(T_MSG* *ppk_msg, ID mbxid, TMO tmout);
extern ER i_tsnd_mbf(ID mbfid, VP msg, INT msgsz, TMO tmout);
extern ER i_trcv_mbf(VP msg, INT *p_msgsz, ID mbfid, TMO tmout);
extern ER i_tcal_por(VP msg, INT *p_rmsgsz, ID porid, UINT calptn, INT cmsgsz, TMO tmout);
extern ER i_tacp_por(RNO *p_rdvno, VP msg, INT *p_cmsgsz, ID porid, UINT acpptn, TMO tmout);
extern ER i_vset_reg(ID tskid, T_REGS *pk_regs, T_EIT *pk_eit, T_CREGS *pk_cregs);
extern ER i_vget_reg(T_REGS *pk_regs, T_EIT *pk_eit, T_CREGS *pk_cregs, ID tskid);
extern ER i_vcre_tsk(T_CTSK *pk_ctsk);
extern ER i_vcre_sem(T_CSEM *pk_csem);
extern ER i_vcre_flg(T_CFLG *pk_cflg);
extern ER i_vcre_mbx(T_CMBX *pk_cmbx);
extern ER i_vcre_mbf(T_CMBF *pk_cmbf);
extern ER i_vcre_por(T_CPOR *pk_cpor);
extern ER i_vcre_mpl(T_CMPL *pk_cmpl);
extern ER i_vcre_mpf(T_CMPF *pk_cmpf);
extern ER i_vdef_cyc(T_DCYC *pk_dcyc);
extern ER i_vdef_alm(T_DALM *pk_dalm);
extern ER i_vcre_pis(ID pisid, T_CPIS *pk_cpis);
extern ER i_vdel_pis(ID pisid);
extern ER i_vvcre_pis(T_CPIS *pk_cpis);
extern ER i_vref_pis(T_RPIS *pk_rpis, ID pisid);
extern ER i_vwai_pis(ID pisid);
extern ER i_vpreq_pis(ID pisid);
extern ER i_vtwai_pis(ID pisid, TMO tmout);
extern ER i_vsig_pis(ID pisid);
extern ER i_vref_tmb(T_RTMB *pk_rtmb, ID tskid);
extern ER i_vrcv_tmb(T_MSG* *ppk_msg);
extern ER i_vprcv_tmb(T_MSG* *ppk_msg);
extern ER i_vtrcv_tmb(T_MSG* *ppk_msg, TMO tmout);
extern ER i_vsnd_tmb(ID tskid, T_MSG *pk_msg);

#endif /* _ISYSCALL_ */
