#! /usr/local/bin/perl
#
# 	    ItIs - ITRON Implementation by Sakamura Lab
# 
# Copyright (C) 1989-1996 by Sakamura Lab, the University of Tokyo, JAPAN
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University nor the names of the laboratory
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE UNIVERSITY OR THE LABORATORY BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
#  @(#) $Id: newversion,v 1.7 1998/01/30 07:14:40 hiro Exp $
#

require "getopt.pl";
do Getopt("cs");

%target_list = (
	"tron/h32",	"H32 SBC System",
	"tron/tvme",	"TVME-150 Board",
	"tron/mcube",	"MCUBE",

	"m68k/dve68k",	"DVE-68K/40 Board",

	"bsd/sunos4",	"SunOS 4.X",
	"bsd/freebsd",	"Free BSD",
);

$target = $opt_c."/".$opt_s;
$TARGET = $target_list{$target} ? $target_list{$target} : "Unknown System";
$DATE = `date`;
$DATE =~ s/  / /g;
chop $DATE;

print <<END_OF_VERSION
char const version[] = "\\nItIs Phase3 Release %d.%d.%d for $TARGET ($DATE)\\n"
"Copyright (C) 1989-1996 by Sakamura Lab, Univ. of Tokyo, JAPAN\\n";
END_OF_VERSION
