#! /usr/local/bin/perl
# 
# 	ItIs - An ITRON Implementation for Research and Education
# 
# Copyright (C) 1989-1997 by Sakamura Laboratory, Univ. of Tokyo, JAPAN
# Copyright (C) 1997-1998 by Embedded and Real-Time Systems Laboratory,
# 				Toyohashi Univ. of Technology, JAPAN
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the universities nor the names of the laboratories
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE UNIVERSITIES OR THE LABORATORIES BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
#  @(#) $Id: deldep,v 1.4 1998/01/30 09:59:34 hiro Exp $
# 

if ($#ARGV != 0) {
	die "Usage: deldep <filename>.\n";
}

$file = $ARGV[0];
$delimiter = '# DO NOT DELETE THIS LINE: makedep depends on it.';

open(INPUT, "$file") || die "Can't open $file.\n";
open(OUTPUT, "> ".$file.".new") || die "Can't open $file.new.\n";
while ($line = <INPUT>) {
	print OUTPUT $line;
	if ($line =~ /$delimiter/) {
		last;
	}
}
close(INPUT);
close(OUTPUT);

if (!rename($file, $file.".old")) {
	die "Can't rename $file to $file.old.\n";
}
if (!rename($file.".new", $file)) {
	die "Can't rename $file.new to $file.\n";
}
