#
# 
# 	ItIs - An ITRON Implementation for Research and Education
# 
# Copyright (C) 1997-1998 by Embedded and Real-Time Systems Laboratory,
# 				Toyohashi Univ. of Technology, JAPAN
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the university nor the name of the laboratory
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE UNIVERSITY OR THE LABORATORY BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
#  @(#) $Id: Makefile.config,v 1.3 1998/07/06 10:48:12 hiro Exp $
# 

#
#  Makefile の共通定義 (68040用)
#

#
#  ディレクトリの定義
#
TOPDIR = /home/proj/m68k/m68k-unknown-aout
LIBDIR = $(TOPDIR)/lib
SFLIBDIR = $(LIBDIR)/msoft-float
INCDIR = $(TOPDIR)/include
ITISINCDIR = $(INCDIR)/itis

#
#  コンパイルフラグ
#
CFLAGS = -O2 -m68040

#
#  コンパイラドライバの定義
#
CC = m68k-gcc
AS = m68k-as
LD = m68k-ld
AR = m68k-ar
RANLIB = m68k-ranlib

#
#  デフォルトコンパイルルールの定義
#
%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.s: %.c
	$(CC) -S $(CFLAGS) $<

%.o: %.S
	$(CC) -c $(CFLAGS) $<
